# host network mode

volumes:
  cachedb.d:

services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    depends_on:
      unbound:
        condition: service_healthy
    network_mode: host
    environment:
      TZ: 'Europe/Prague'
      FTLCONF_dns_listeningMode: 'all'
      FTLCONF_dns_upstreams: "127.0.0.1#5335"
      FTLCONF_misc_etc_dnsmasq_d: 'true'
      FTLCONF_webserver_port: '8080'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/opt/docker/pihole-unbound-redis/etc-pihole:/etc/pihole'
      - '/opt/docker/pihole-unbound-redis/etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
      - NET_BIND_SERVICE
      - CAP_SYS_TIME
    restart: always

  unbound:
    container_name: unbound
    hostname: unbound
    image: madnuttah/unbound:latest
    network_mode: host
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/opt/docker/pihole-unbound-redis/unbound/unbound.conf:/usr/local/unbound/unbound.conf'
      - '/opt/docker/pihole-unbound-redis/unbound/conf.d/:/usr/local/unbound/conf.d/'
      - '/opt/docker/pihole-unbound-redis/unbound/log.d/:/usr/local/unbound/log.d/'
      - '/opt/docker/pihole-unbound-redis/unbound/zones.d/:/usr/local/unbound/zones.d/'
      - '/opt/docker/pihole-unbound-redis/unbound/iana.d/:/usr/local/unbound/iana.d/'
      - '/opt/docker/pihole-unbound-redis/redis/healthcheck.sh:/usr/local/unbound/sbin/healthcheck.sh'
      - 'cachedb.d:/usr/local/unbound/cachedb.d/'
    environment:
      TZ: "Europe/Prague"
      HEALTHCHECK_PORT: 5335
      EXTENDED_HEALTHCHECK: true
      EXTENDED_HEALTHCHECK_DOMAIN: "nlnetlabs.nl"
      ENABLE_STATS: true
      DISABLE_SET_PERMS: true
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: /usr/local/unbound/sbin/healthcheck.sh
      interval: 60s
      retries: 5
      start_period: 15s
      timeout: 30s
    restart: always

  redis:
    container_name: redis
    image: redis:alpine
    hostname: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
      - '/opt/docker/pihole-unbound-redis/redis/data:/data'
      - '/opt/docker/pihole-unbound-redis/redis/redis.conf:/usr/local/etc/redis/redis.conf'
      - '/opt/docker/pihole-unbound-redis/redis/healthcheck.sh:/usr/local/sbin/healthcheck.sh'
      - 'cachedb.d:/usr/local/unbound/cachedb.d/'
    healthcheck:
      test: /usr/local/sbin/healthcheck.sh
      interval: 10s
      retries: 3
      start_period: 5s
      timeout: 15s
    depends_on:
      - redis-socket
    network_mode: host
    restart: always


  redis-socket:
    image: busybox
    container_name: redis-socket
    init: true
    tty: true
    command: /bin/sh -c "chown -R 999:1000 /usr/local/unbound/cachedb.d/"
    volumes:
      - 'cachedb.d:/usr/local/unbound/cachedb.d/'
    restart: no
